name: Build OpenWrt X64

on:
#  release:
#    types: [published]
  push:
    branches:
      - master
    paths:
      - 'start'
  schedule:
    - cron: 0 18 * * *
#  watch:
#    types: [started]

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: config/x64.config
  DIY_SH: diy.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Date
      run: |
         date=$(date +%Y-%m-%d)
         echo "::set-env name=DATE::$date"


 

    - name:  Push dl
      env:
       SUPER_TOKEN: ${{ secrets.SUPER_TOKEN }}
      run: |
        cd openwrt/dl
        touch test
        git init
        git config user.name "bot"
        git config user.email "bot@github.com"
        git add .
        git commit -m "(TZ='Asia/Shanghai' date +@%Y%m%d)"
        git push --force --quiet https://$SUPER_TOKEN@github.com/hyird/action-openwrt.git  HEAD:dl
        

